### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jburel**
* Add license header
* Fix url preventing the container to be built.

To test:
* Check that you can run the notebook

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
When I run this separately (without https://github.com/ome/omero-guide-trackmate/pull/2), I get the same error as reported on https://github.com/ome/omero-guide-trackmate/pull/2#issuecomment-868431450 - so I think the problem is introduced in this PR

**Comment by pwalczysko** [comment]
When this notebook is run in MyBinder, then the following cell (see screenshot) hangs forever with the star signifying not being done.

Screenshot 2021-06-25 at 12 29 06

**Comment by jburel** [comment]
See https://github.com/ome/omero-guide-trackmate/pull/2#issuecomment-868438726 cf. building locally

I will check what is happening with the cell.

**Comment by pwalczysko** [comment]
cleaned the docker on my laptop, was able to build the notebook. Then, crashed on the Create Trackmate model cell with

``Exception in thread "TrackMate spot detection thread 1/4" java.lang.OutOfMemoryError: Java heap space``

**Comment by pwalczysko** [comment]
the problem on MyBinder with the "add to classpath" cellls reported in https://github.com/ome/omero-guide-trackmate/pull/4#issuecomment-868433197 did not repeat when the notebook was built the second time

**Comment by pwalczysko** [comment]
Restarted my laptop, then built again locally, this time I got

```
Error: cannot open display: :1.0
[W 13:51:34.034 NotebookApp] 400 GET /api/contents/notebooks/tracking.ipynb?type=notebook&_=1624629093898 (172.17.0.1): Unreadable Notebook: /home/pwalczysko/notebooks/tracking.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
```

**Comment by jburel** [comment]
The problem

> Restarted my laptop, then built again locally, this time I got
> 
> ```
> Error: cannot open display: :1.0
> [W 13:51:34.034 NotebookApp] 400 GET /api/contents/notebooks/tracking.ipynb?type=notebook&_=1624629093898 (172.17.0.1): Unreadable Notebook: /home/pwalczysko/notebooks/tracking.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
> 
This is an issue in the other PR.
I will push a commit.

**Comment by pwalczysko** [comment]
Ran the notebook successfully to the end. Also the PR https://github.com/ome/omero-guide-trackmate/pull/2 was merged.
The trick was to use much smaller image as not to run out of heapspace https://workshop.openmicroscopy.org/webclient/img_detail/28629/?dataset=2383
Ready to merge fmpov.

**Pull request merged**
